### ISSUE TITLE
How to detect array elements?

### ISSUE THREAD

**Issue by science** [dgraham/yajl-ffi#1]
First off, I love the idea of this gem - I've got a 5gb json text file I need to deal with and this project is my great hope! Sorry to leave an issue that isn't bug/issue - this is more of a support request, but I didn't see another way to reach you. Feel free to close this if it's not suitable to contact you this way..

The data structure I'm processing (in simplified form) looks like this:

```
{"total_rows":1483483,"offset":0,"rows":[{"item1": "here"},{"item2": ["here", "also"]} ]}
```

What I want to do is basically grab all the contents of each item (item1, item2, etc) and process them. For now I might save each item to an individual file but later I might parse them as I go.

I'm not sure if/how I can detect/get those larger array element structures/events from your system - I don't see an event for "hash closed" or "next array element" - is there a way to detect this, that I'm not seeing? Or is there a technique for saving enough streaming data in a temp variable to detect this kind of transition?

Thanks for any advice and again apologies for putting this in an issue ticket..

**Comment by science** [comment]
As I think about this problem more and talk with another developer about it, I think there is a feature that would make using your streaming library easier for many common use cases (including mine).

If I could turn on/off a "string stream capture" feature, that would let me process events that I care about and then capture json structures as strings when I know I'm getting data I want. Then I could parse that string (when the event ends) using traditional json parsers (since these "sub-strings" in many cases, and definitely in mine, are known/manageable sizes).

Something like:

``` ruby
buffer = ""
@parse.start_object { |o|
  if o == something_i_care_about then
    @parse.stream_to(buffer)
  end
}
@parse.end_object { |o|
  if o == something_i_care_about then
    @parse.stop_streaming
    custom_process_buffer(buffer)
    buffer = ""
  end
}
```

Is that a crazy approach?

**Comment by dgraham** [comment]
The key to filtering large documents is using a stack to track how deep into the parse tree we are. The [Builder](https://github.com/dgraham/yajl-ffi/blob/master/lib/yajl/ffi/builder.rb) class uses a stack to build a full object in memory. We can subclass it to detect when the `rows` array is being filled with parsed objects, and then notify observers of the row event.

This subclass buffers 100 row objects and then notifies the observers for that chunk of rows.

``` ruby
class RowFilter < Yajl::FFI::Builder
  MAX_ROWS = 100

  def initialize(parser, &block)
    @listeners = Hash.new {|h, k| h[k] = [] }
    super(parser)
    instance_eval(&block) if block_given?
  end

  def rows(&block)
    @listeners[:rows] << block
  end

  def notify(rows, done)
    @listeners[:rows].each do |block|
      block.call(rows, done)
    end
  end

  def end_document
    notify(@stack.pop['rows'], true)
  end

  def end_object
    super

    # Row object complete.
    if @stack.size == 2 && @stack[-1].size >= MAX_ROWS
      notify(@stack.pop, false)
      @stack.push([])
    end
  end
end

parser = Yajl::FFI::Parser.new
filter = RowFilter.new(parser) do
  rows do |rows, complete|
    # Process rows, complete tells us if this is the last row.
  end
end

json = %q{
  {
    "total_rows": 1483483,
    "offset": 0,
    "rows":[
      {"item1": "here"},
      {"item2": ["here", "also"]}
    ]
  }
}

# This is where we can pass chunks of a large file to the
# parser. This example just passes the full JSON document all at once.
parser << json
```

I'm glad you found the gem useful!

**Comment by science** [comment]
Thanks. Wow. I didn't expect a coded solution. Hopefully this ticket will be useful to others as well - it is certainly very useful for me! Thanks again.

**Comment by aunghtain** [comment]
This should be in README. I'm glad I look in the issues section.
