### ISSUE TITLE
Cannot use on RHEL6

### ISSUE THREAD

**Issue by thisismydesign** [dgraham/yajl-ffi#2]
Had the issue described in 'Library loading':
Could not open library 'yajl': yajl: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libyajl.so': libyajl.so: cannot open shared object file: No such file or directory.
Could not open library 'libyajl.so.2': libyajl.so.2: cannot open shared object file: No such file or directory
This persisted even after providing LD_LIBRARY_PATH (install location found based on this: http://stackoverflow.com/questions/1766380/determining-the-path-that-a-yum-package-installed-to)

Found a similar problem where they recommended to install yajl-devel:
http://serverfault.com/questions/703809/virsh-error-loading-shared-libraries-libyajl-so-2-is-missing

After that lib is found but I'm getting the following error:
/usr/local/rvm/gems/ruby-2.2.1/gems/ffi-1.9.10/lib/ffi/library.rb:261:in `attach_function': Function 'yajl_config' not found in [libyajl.so](FFI::NotFoundError)

**Comment by dgraham** [comment]
RHEL 6 may ship with libyajl version 1 rather than version 2. Does [compiling libyajl](https://github.com/dgraham/yajl-ffi#source) from source work?

**Comment by thisismydesign** [comment]
You're right. I also noticed since that you mentioned specifically libyajl2 as dependency.
Thank you for your help.
